### ISSUE TITLE
IMPACT OF DEMOGRAPHIC FACTORS ON LIFE INSURANCE PREMIUM PRICING:

### ISSUE THREAD

**Issue by TravisBoltz** [jnopareboateng/ml-library#13]
This study examines how demographic factors like age, gender, and policy type impact life insurance premium pricing. It aims to help insurers set more accurate premiums by analyzing data from policyholders in Ghana.

**Comment by TravisBoltz** [comment]
I have uploaded the the initial sate to the drive. Check it and make the necessary changes to it.

**Comment by jnopareboateng** [comment]
Awesome stuff!
